apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-shell
  title: TEST Shell
  description: Test execute shell function
spec:
  type: service
  parameters:
    - title: Bash Script Execution
      required:
        - scriptPath
      properties:
        scriptPath:
          type: string
          title: Path to Bash Script
          description: The relative or absolute path to the bash script to execute
        additionalParams:
          type: array
          title: Additional Parameters
          description: Optional additional parameters for the bash script
          items:
            type: string
  steps:
    - id: run-bash-script
      name: Run Custom Bash Script
      action: custom:run:bashScript
      input:
        scriptPath: ${{ parameters.scriptPath }}
        additionalParams: ${{ parameters.additionalParams }}
        